.checkov.yaml
.devops/deploy-pipelines.yml
.github/workflows/check_helm.yml
helm/templates/configmap.yaml
helm/templates/deployment.yaml
helm/templates/service.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

feat: Enable checkov

---

README.md
charts/microservice-chart/Chart.yaml
charts/microservice-chart/templates/deployment.yaml
charts/microservice-chart/templates/service.yaml
charts/microservice-chart/values.yaml
examples/spring-boot-app/helm/Chart.lock
examples/spring-boot-app/helm/Chart.yaml
examples/spring-boot-app/helm/values-dev.yaml

Live & ready probe updated configuration to allow applications that take time to start to now restart every time

feat: Probe updated configuration

---

charts/microservice-chart/templates/autoscaling.yaml

try the suggestion from https://github.com/kedacore/keda/issues/606#issuecomment-582029224

fix: Try to fix autoscale

---

charts/microservice-chart/README.md

chore(docs): Update Readme

---

charts/microservice-chart/Chart.yaml
charts/microservice-chart/README.md
charts/microservice-chart/templates/deployments.yaml
charts/microservice-chart/values.yaml

feat: Permit to add sidecars

---

charts/microservice-chart/Chart.yaml

- fix version in helm
upgrade release version

breaking: Upgrade to 2.0.0 version

---

README.md
charts/microservice-chart/README.md
charts/microservice-chart/templates/beta-configmap.yaml
charts/microservice-chart/templates/beta-secretproviderclass-kv.yaml
charts/microservice-chart/templates/configmap.yaml
charts/microservice-chart/values.yaml
examples/spring-boot-app-bar-latest/helm/.helmignore
examples/spring-boot-app-bar-latest/helm/Chart.lock
examples/spring-boot-app-bar-latest/helm/Chart.yaml
examples/spring-boot-app-bar-latest/helm/templates/configmaps.yaml
examples/spring-boot-app-bar-latest/helm/values-dev.yaml
examples/spring-boot-app-bar-latest/helm/values-devopslab-dev.yaml
examples/spring-boot-app-bar-latest/helm/values-rtd-dev.yaml
examples/spring-boot-app-bar/helm/values-devopslab-dev.yaml

- configmaps and beta-confingmaps now manage empty values
- beta-serviceproviderclass-kv fix typo
- values: fix canary attributes
Allow the helm chart to work with version 2.0 values

fix: Fix retro compatibility with v2.0

---

README.md
charts/microservice-chart/templates/beta-deployment.yaml
charts/microservice-chart/templates/deployments.yaml
charts/microservice-chart/values.yaml

* add handlerType for liveness and readiness
*livenessProbe*
*readinessProbe*
Now chose if enable tcpSocket ot httpGet 
```yaml
livenessProbe:
handlerType: httpGet <httpGet|tcpSocket>
readinessProbe:
handlerType: httpGet <httpGet|tcpSocket>
```

feat: Choose handlerType for liveness and readiness

---

charts/microservice-chart/templates/beta-deployment.yaml
charts/microservice-chart/templates/beta-secretproviderclass-kv.yaml
charts/microservice-chart/templates/deployments.yaml
charts/microservice-chart/templates/secretproviderclass-kv.yaml

* remove check on volumet
* add if confition on secret provider

feat: Fix big volume tmp, secret provider

---

charts/microservice-chart/templates/beta-deployment.yaml

feat: Fix canary deployment

---

charts/microservice-chart/templates/autoscaling.yaml
charts/microservice-chart/values.yaml

feat: Autoscaling advanced beahvior

---

charts/microservice-chart/templates/_helpers.tpl
charts/microservice-chart/templates/beta-deployment.yaml
charts/microservice-chart/templates/deployments.yaml

feat: Fix version

---

charts/microservice-chart/README.md
charts/microservice-chart/values.yaml

- revert default values for ingress rewrite
- docs update
Avoid problems with previuos version of the charts

fix: Ingress rewrite default values is $1

---

.github/workflows/release.yml

feat: Upgrated semantic release version

---

.github/workflows/release-manual.yml
.github/workflows/release.yml
README.md

- added LTS documentation
- added manual release for lts release
Allow to release LTS versions

chore: LTS documentation and manual release

---

.tool-versions

fix: Force release

---

charts/microservice-chart/templates/_helpers.tpl

removed `microservice-chart` from the names of deployments.
To improve the human readability 
We want remove the useless `microservice-chart` from the name of the deployments as `cache-oracle` in the example:

chore: Clear name

---

MIGRATION_GUIDE.md
README.md
charts/microservice-chart/README.md
charts/microservice-chart/templates/_helpers.tpl
charts/microservice-chart/values.yaml
examples/spring-boot-app-bar-latest/helm/values-devopslab-dev.yaml
tests/v2-migration-java-helm-complete-test/helm/.helmignore
tests/v2-migration-java-helm-complete-test/helm/Chart.yaml
tests/v2-migration-java-helm-complete-test/helm/run-migration.sh
tests/v2-migration-java-helm-complete-test/helm/run.sh
tests/v2-migration-java-helm-complete-test/helm/templates/configmaps.yaml
tests/v2-migration-java-helm-complete-test/helm/v5-values-devopslab-dev.yaml
tests/v2-migration-java-helm-complete-test/helm/values-devopslab-dev.yaml
tests/v5-java-helm-basic-test/helm/Chart.lock
tests/v5-java-helm-basic-test/helm/Chart.yaml
tests/v5-java-helm-basic-test/helm/values-devopslab-dev.yaml
tests/v5-java-helm-complete-test/helm/Chart.lock
tests/v5-java-helm-complete-test/helm/Chart.yaml
tests/v5-java-helm-complete-test/helm/values-devopslab-dev.yaml

- rollback of names, to not broke reto-compatibility
- default: added tmp folder from values
- fix: selectorLabels to not broke reto-compatibility
- tests: created v2-migration-java-helm-complete-test to test migration from v2.3.1 to 5.x
- tests: fix v5 tests
- docs: added migration guide to help migration from v2 to v5.3

feat: Migration from v2 to v5 complete

---

.gitignore
charts/microservice-chart/README.md
tests/v2-migration-java-helm-complete-test/helm/Chart.lock
tests/v2-migration-java-helm-complete-test/helm/Chart.yaml
tests/v5-java-helm-basic-test/helm/Chart.lock
tests/v5-java-helm-basic-test/helm/Chart.yaml
tests/v5-java-helm-complete-test/helm/Chart.lock
tests/v5-java-helm-complete-test/helm/Chart.yaml

Update the charts versions for tests projects

fix: Update chart locks for tests

---

.pre-commit-config.yaml
charts/microservice-chart/README.md
charts/microservice-chart/templates/deployments.yaml
charts/microservice-chart/values.yaml
tests/v5-java-helm-complete-test-bar/helm/Chart.lock
tests/v5-java-helm-complete-test-bar/helm/Chart.yaml
tests/v5-java-helm-complete-test-bar/helm/values-devopslab-dev.yaml
tests/v5-java-helm-complete-test-foo/helm/Chart.lock
tests/v5-java-helm-complete-test-foo/helm/Chart.yaml

- added startupProbe
- for all probe now you can use exec command
- for all probe you can disable one or more
- updated docs
- updated tests suite for example
Allow to use all the probes and the feature that offers

feat: liveness & readiness probe optional + starupProbe and exec commands

---

CHANGELOG
charts/microservice-chart/README.md
charts/microservice-chart/templates/deployments.yaml
charts/microservice-chart/values.yaml
tests/v5-java-helm-complete-test-bar/helm/Chart.lock
tests/v5-java-helm-complete-test-bar/helm/Chart.yaml
tests/v5-java-helm-complete-test-bar/helm/values-devopslab-dev.yaml

- Added container.[command|args] options
- fix: probe typo

feat: 108-allow-override-of-container-specs-command-and-args-properties

---

README.md
charts/microservice-chart/README.md
tests/v5-java-helm-complete-test-bar/helm/Chart.lock
tests/v5-java-helm-complete-test-bar/helm/Chart.yaml
tests/v5-java-helm-complete-test-bar/helm/values-devopslab-dev.yaml
tests/v5-java-helm-complete-test-foo/helm/Chart.lock
tests/v5-java-helm-complete-test-foo/helm/Chart.yaml
tests/v5-java-helm-complete-test-foo/helm/values-devopslab-dev.yaml

feat: Added Tolerations to docs

---

README.md
charts/microservice-chart/templates/deployments.yaml
charts/microservice-chart/values.yaml
tests/v5-java-helm-complete-test-foo/helm/Chart.lock
tests/v5-java-helm-complete-test-foo/helm/Chart.yaml
tests/v5-java-helm-complete-test-foo/helm/values-devopslab-dev.yaml

- `externalConfigMapFiles` now is possible to define a custom mount point
- better documentation
- test updated
Allow to choose where to put the file mounted from configmap

feat: Added for external configmap custom mount point

---

MIGRATION_GUIDE.md
README.md

chore: Updated migration documentation

---

charts/microservice-chart/README.md
charts/microservice-chart/values.yaml

added meta tags to allow to configure postman-test inside the pipelines

chore: Added postman meta tags

---

CHANGELOG
charts/microservice-chart/README.md
charts/microservice-chart/templates/deployments.yaml
charts/microservice-chart/values.yaml
tests/v5-java-helm-basic-test/helm/Chart.lock
tests/v5-java-helm-basic-test/helm/Chart.yaml
tests/v5-java-helm-complete-test-bar/helm/Chart.lock
tests/v5-java-helm-complete-test-bar/helm/Chart.yaml
tests/v5-java-helm-complete-test-foo/helm/Chart.lock
tests/v5-java-helm-complete-test-foo/helm/Chart.yaml

- updated test suite
- added revisionHistoryLimit to deployment
- docs
The default revisionHistoryLimit was 10, that make too much noise when you want to analize the replica sets

feat(Deployment): added revisionHistoryLimit to configure the number of revisions 

---

README.md
charts/microservice-chart/README.md
charts/microservice-chart/templates/deployments.yaml
tests/v5-java-helm-basic-test/helm/Chart.lock
tests/v5-java-helm-basic-test/helm/Chart.yaml
tests/v5-java-helm-basic-test/helm/values-devopslab-dev.yaml

the values and the actual usage of forceRedeploy was wrong

fix(Deployment): forceRedeploy value inside deployment

---

.github/workflows/pre-commit-checks.yml
charts/microservice-chart/README.md

fix: pre-commit run with different options depending on branch

---

charts/microservice-chart/README.md
scripts/deploy.sh
tests/v5-java-helm-basic-test/helm/Chart.lock
tests/v5-java-helm-basic-test/helm/Chart.yaml
tests/v5-java-helm-basic-test/helm/values-devopslab-dev.yaml
tests/v5-java-helm-complete-test-bar/helm/Chart.lock
tests/v5-java-helm-complete-test-bar/helm/Chart.yaml
tests/v5-java-helm-complete-test-bar/helm/values-devopslab-dev.yaml
tests/v5-java-helm-complete-test-canary/helm/values-devopslab-dev.yaml
tests/v5-java-helm-complete-test-foo/helm/Chart.lock
tests/v5-java-helm-complete-test-foo/helm/Chart.yaml
tests/v5-java-helm-complete-test-foo/helm/values-devopslab-dev.yaml

Use the cron to zero during not working hours

chore: PAYMCLOUD-194-keda-studio-configurazione-con-zero-pod

---

README.md
charts/microservice-chart/README.md
charts/microservice-chart/values.yaml

Allow to have a postman documentation more clear

chore: Updated postman documentation

---

charts/microservice-chart/Chart.yaml
charts/microservice-chart/README.md

chore: Revert chart version to 7.3.1 to preform pipe release.

---

CHANGELOG

thx to https://github.com/pagopa/aks-microservice-chart-blueprint/pull/143
@pasqualespica

fix: range iterator logic for configMapFromFile
